apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cmsample1
  name: cmsample1
spec:
  containers:
  - image: nginx
    name: cmsample1
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: sampleconfigmap
          key: kidambi
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
