apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: jobsample1
spec:
  parallelism: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - echo
        - sample job
        image: busybox
        name: jobsample1
        resources: {}
      restartPolicy: Never
status: {}
