apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: /var/log
  name: multi-cont-pod
spec:
  containers:
  - image: busybox
    name: multi-cont-pod
    command: ["/bin/sh"]
    args: ["-c"," while true; do echo 'Hi I am from Main container'>> /var/log/index.html; sleep 5; done "]
    resources: {}
    volumeMounts:
    - name:  var-logs
      mountPath:  /var/log
  - image: nginx
    name: sidecar-container
    resources: {}
    ports:
      - containerPort: 80
    volumeMounts:
    - name:  var-logs
      mountPath:  /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Never
# 
  volumes:
  - name:   var-logs
    hostPath:
        path:  /var/run/docker.sock
        type: Socket
status: {}
