apiVersion: v1
kind: Pod
metadata:
  # creationTimestamp: null
  labels:
    run: sknodeapp
  name: sknodeapp
spec:
  # volumes:
  #   - name: html
  #     emptyDir: {}
        
  containers:
  - image: sridharkidambi/skapp
    name: sknodeapp
    # volumeMounts:
    #   - name:  html
    #     mountPath:  /usr/share/nginx/html
    #     readOnly: true
    # resources: {}
    # livenessProbe:
    #   exec:
    #     command:
    #     - cat
    #     - tmp/healthy
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # - image: alpine
  #   name: html-updater
  #   command: ["/bin/sh","-c"]
  #   args:
  #     - while true; do date >> /html/index.html;
  #       sleep 10; done
  #   volumeMounts:
  #     - name:  html
  #       mountPath: /html

#   dnsPolicy: ClusterFirst
#   restartPolicy: Always
# status: {}
