apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-09-03T05:25:52Z"
  labels:
    run: pvsample
  name: pvsample
  namespace: default
  resourceVersion: "409019"
  uid: bb46a37d-0b95-49a1-865e-684be7664ece
spec:
  containers:
  - args:
    - '-'
    - o
    - yaml
    image: nginx
    imagePullPolicy: Always
    name: pvsample
    ports:
      - containerPort: 80
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pvclaim-sample
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: pvclaim-sample
    persistentVolumeClaim:
      claimName: pvclaim-sample 
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-03T05:25:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-09-03T05:25:52Z"
    message: 'containers with unready status: [pvsample]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-09-03T05:25:52Z"
    message: 'containers with unready status: [pvsample]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-09-03T05:25:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://908b7451dafc3ec5c52656fb8fce599e593e2c6bb0a1b112b8dad582bb298d06
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:4d4d96ac750af48c6a551d757c1cbfc071692309b491b70b2b8976e102dd3fef
    lastState:
      terminated:
        containerID: docker://908b7451dafc3ec5c52656fb8fce599e593e2c6bb0a1b112b8dad582bb298d06
        exitCode: 127
        finishedAt: "2021-09-03T05:26:00Z"
        reason: Error
        startedAt: "2021-09-03T05:26:00Z"
    name: pvsample
    ready: false
    restartCount: 1
    started: false
    state:
      waiting:
        message: back-off 10s restarting failed container=pvsample pod=pvsample_default(bb46a37d-0b95-49a1-865e-684be7664ece)
        reason: CrashLoopBackOff
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.17
  podIPs:
  - ip: 172.17.0.17
  qosClass: BestEffort
  startTime: "2021-09-03T05:25:52Z"
