apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mybusybox
  name: mybusybox
spec:
  serviceAccountName: admin
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: mybusybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
