apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx12
  name: nginx12
spec:
  nodeSelector:
    name: minikube
  containers:
  - args:
    - restart=Never
    image: nginx
    name: nginx12
    resources: {}
  - restart=Never
    image: nginx
    name: nginx12
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
