apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secbusybox
  name: secbusybox
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: secbusybox
    securityContext:
      runAsUser: 1001
      runAsGroup: 2001
      capabilities:
        add:  ["NET_ADMIN" , "SYS_TIME"]
    envFrom:
      - secretRef:
          name: my-secret
    # env:
    # - name:  USER_NAME
    #   valueFrom: 
    #     secretRef:
        # secretKeyRef:
        #   name: my-secret
        #   key: username
    resources: 
      requests:
        memory: "100Mi"
        cpu: "0.5"
      limits:
        memory: "200Mi"  
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
