apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sknix
  name: sknix
spec:
  containers:
  - image: nginx
    name: sknix
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 25
    livenessProbe:
      httpGet:
        path: /healthZ
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 25
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
