apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleservice
  name: sampleservice
spec:
  type: NodePort
  selector: 
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9736



