apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: volumecm
  name: volumecm
spec:
  containers:
  - image: nginx
    name: volumecm
    volumeMounts:
      - mountPath: /etc/cfg
        name: nginx-volume
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name:  nginx-volume
    configMap:
      name: cfgvolume
status: {}



  
