apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: livreadytest
  name: livreadytest
spec:
  containers:
  - image: nginx:latest
    name: livreadytest
    resources: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 25
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 25    
      
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
