apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testliveness
  name: testliveness
spec:
  containers:
  - image: nginx
    name: testliveness
    resources: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
