apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testprobe
  name: testprobe
spec:
  containers:
  - image: nginx
    name: testprobe
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        port: 80
        path: /
    livenessProbe:
      httpGet:
        port: 80
        path: /
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never 
status: {}
