apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: envpod
  name: envpod
spec:
  containers:
  - image: nginx
    name: envpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
