apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-10-09T18:57:38Z"
  labels:
    run: maincontainer
  name: mainone
  namespace: default
  resourceVersion: "688295"
  uid: 3efa67aa-9dbf-46ba-8ed2-281930f453cf
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep
      5; done
    image: busybox
    imagePullPolicy: Always
    name: maincontainer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: emptydirvolume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6sgv8
      readOnly: true
  - image: nginx
    imagePullPolicy: Always
    name: sidecontainer
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: emptydirvolume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6sgv8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: emptydirvolume
  - name: default-token-6sgv8
    secret:
      defaultMode: 420
      secretName: default-token-6sgv8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-10-09T18:57:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-10-09T18:57:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-10-09T18:57:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-10-09T18:57:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c70794f5725259d1bb0c1391ee01d28660982d38f9402ab349ee86be7e697457
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:52f73a0a43a16cf37cd0720c90887ce972fe60ee06a687ee71fb93a7ca601df7
    lastState: {}
    name: maincontainer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-10-09T18:57:42Z"
  - containerID: docker://74611509e435f349ddfa76a9975947ad817129076e1f6bd323555d7761c0f4d2
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:06e4235e95299b1d6d595c5ef4c41a9b12641f6683136c18394b858967cd1506
    lastState: {}
    name: sidecontainer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-10-09T18:57:46Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.7
  podIPs:
  - ip: 172.17.0.7
  qosClass: BestEffort
  startTime: "2021-10-09T18:57:38Z"
