apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: mycronjob1
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: mycronjob1
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date;echo hello from kubernetes cluster
            image: busybox
            name: mycronjob1
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
