apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: maincontainer
  name: mainone
spec:
  volumes:
    - name: emptydirvolume
      emptyDir: {}
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep
      5; done
    image: busybox
    name: maincontainer
    volumeMounts:
      - mountPath: /var/log
        name: emptydirvolume
  - image: nginx
    name: sidecontainer
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: emptydirvolume
    ports:
      - containerPort: 80

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
