apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mypv
  name: mypv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

