apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pvcmodule
  name: pvcmodule
spec:
  volumes:
    - name: task-pv-claim-use
      persistentVolumeClaim:
        claimName: mypvc
  containers:
  - image: nginx
    name: pvcmodule
    volumeMounts:
      - name: task-pv-claim-use
        mountPath: "/usr/share/nginx/html"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
