apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "6"
      deployment.kubernetes.io/max-replicas: "8"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2021-10-10T02:42:53Z"
    generation: 2
    labels:
      app: skwebapp
      pod-template-hash: d4b969fd9
    name: skwebapp-d4b969fd9
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: skwebapp
      uid: 486d68f6-a81d-40f2-8a1b-f3a22deef815
    resourceVersion: "697067"
    uid: 7f1dc1c5-20af-4ebc-bcf3-11f394dcd6c4
  spec:
    replicas: 6
    selector:
      matchLabels:
        app: skwebapp
        pod-template-hash: d4b969fd9
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: skwebapp
          pod-template-hash: d4b969fd9
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 6
    fullyLabeledReplicas: 6
    observedGeneration: 2
    readyReplicas: 6
    replicas: 6
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
