apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: ibusybox1
spec:
  template:
    metadata:
      creationTimestamp: null
    
    spec:
      completions: 10
      parallelism: 10
      containers:
      - command:
        - /bin/sh
        - -c
        - echo Hello I am from job
        image: busybox
        name: ibusybox1
        resources: {}
      restartPolicy: Never
status: {}
