apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testmedeploy
  name: testmedeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testmedeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testmedeploy
    spec:
      containers:
      - image: nginx:1.17.1
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
