apiVersion: v1
kind: Service
metadata:
  name: myappservice
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30004
  selector:
    name: skapp
