apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" 
    name: "sample"
  storageClassName: manual

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce



