apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" 
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
