apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  volumes:
    - name: mountedspace
      emptyDir: {}        
  containers:
  - image: redis
    volumeMounts:
      - name: mountedspace
        mountPath: /data/redis
        
    name: redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
