apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: echojob1
spec:
  completions: 10
  parallelism : 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - echo
        - Hello I am from job
        image: busybox
        name: echojob1
        resources: {}
      restartPolicy: Never
status: {}
