apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podnodeslector
  name: podnodeslector
spec:
  nodeSelector:
    nodeName: nginxnode
  containers:
  - args:
    - restart=Never
    image: nginx
    name: podnodeslector
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
