apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: allsecret
  name: allsecret
spec:
  containers:
  - image: nginx
    name: allsecret
    resources: {}
    envFrom:
      - secretRef:
         name: "mysecret"
      - configMapRef:
         name: "envcfgmap"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
