apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: capabilitypod
  name: capabilitypod
spec:
  containers:
  - args:
    - restart=Never
    - /bin/sh
    image: nginx
    name: capabilitypod
    securityContext:
      capabilities: 
        add: ['NET_ADMIN' , 'SYS_TIME']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
