apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mempod
  name: mempod
spec:
  containers:
  - image: nginx
    name: mempod
    resources: 
      requests:
        memory: "100Mi"
        cpu: "0.5"
      limits:
        memory: "200Mi"
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
