apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mycmfile
  name: mycmfile
spec:
  containers:
  - image: nginx
    name: mycmfile
    envFrom:
      - configMapRef:
          name: myconfigmap
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
