apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretimage
  name: secretimage
spec:
  containers:
  - image: nginx
    name: secretimage
    env:
      - name: "secrets"
        valueFrom:
            secretKeyRef:
              key: "password"
              name: "mysecret"
    resources: 
      requests:
        memory: "20Mi"
        cpu: ".25"
      limits:
        memory : "20Mi"
        cpu: ".25"

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
