apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynginx
  name: mynginx
spec:
  containers:
  - image: nginx
    name: mynginx
    volumeMounts:
       - name: nginx-volume
         mountPath: /etc/cfg
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name:  nginx-volume
      configMap:
        name: cfgvolume
status: {}
